#!/usr/bin/env bash

source ./install-common

PLUGINS_DIR="dotbot-plugins"

"${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -p "${PLUGINS_DIR}"/dotbot-yay/yay.py -d "${BASE_DIR}" -c "${BASE_DIR}/${CONFIG_DIR}/${1}${CONFIG_SUFFIX}"
