- defaults:
    link:
        relink: true
        create: true
- clean: ['~']
- link:
    ~/.zimrc:
    ~/.zshrc:
    ~/.vimrc:
    ~/.zshenv:
    ~/.zlogin:
    ~/.p10k.zsh:
    ~/.Xresources:
    ~/.config/nvim/init.vim: 
        path: config/nvim/init.vim
    ~/.config/chromium-flags.conf:
        path: config/chromium-flags.conf
    ~/.config/systemd/user/:
        glob: true
        path: units/*
