- defaults:
    link:
      relink: true
      create: true
- clean: ["~"]
- link:
    ~/.zimrc:
    ~/.zshrc:
    ~/.zshenv:
    ~/.zlogin:
    ~/.p10k.zsh:
    ~/.Xresources:
    ~/.config/nvim:
      path: config/nvim
    ~/.config/chromium-flags.conf:
      path: config/chromium-flags.conf
    ~/.config/brave-flags.conf:
      path: config/brave-flags.conf
    ~/.config/systemd/user/:
      glob: true
      path: units/*
    ~/.local/share/dbus-1/services:
      glob: true
      path: dbus-1/services/*
